# Generated by Django 4.1.3 on 2023-04-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboaard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
    ]
